service: strain-hunter
app: strain-hunter
org: jordmax12
frameworkVersion: '^3'
configValidationMode: error

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  architecture: arm64
  memorySize: 512
  environment:
    STAGE: ${sls:stage}
    REGION: ${aws:region}
    ALGOLIA_API_KEY: ${ssm:/ALGOLIA_API_KEY}
    CLICK_SEND_BASIC_AUTH: ${ssm:/CLICK_SEND_BASIC_AUTH}
    TARGETS_TRACKER_TABLE: !Ref TargetsTrackerTable
    USERS_TABLE: !Ref UsersTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:*
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - cloudwatch:*
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - !Sub "${TargetsTrackerTable.Arn}"
            - !Sub "${TargetsTrackerTable.Arn}/index/*"
            - !Sub "${UsersTable.Arn}"
            - !Sub "${UsersTable.Arn}/index/*"

resources: ${file(resources.yml)}

functions:
  getTargets:
    handler: get-targets.handler
    name: rps-get-targets
    timeout: 900
    # events:
    #   - schedule: rate(1 hour)
      # everyday at 8:00 AM UTC (12 AM PST)
      # - schedule: cron(00 16 ? * * *)
  targetSMSListener:
    handler: target-sms-listener.handler
    name: rps-target-sms-listener
    timeout: 900
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt TargetsTrackerTable.StreamArn
          batchSize: 100
          startingPosition: LATEST
          maximumRetryAttempts: 3
          filterPatterns:
            - eventName: [INSERT]
  targetEmailListener:
    handler: target-email-listener.handler
    name: rps-target-email-listener
    timeout: 900
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt TargetsTrackerTable.StreamArn
          batchSize: 100
          startingPosition: LATEST
          maximumRetryAttempts: 3
          filterPatterns:
            - eventName: [INSERT]

plugins:
  - serverless-plugin-monorepo
