name: CI

on:
  pull_request:
    branches: [main, prod]
  workflow_dispatch:

jobs:
  test_coverage_and_sonarcloud:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - run: yarn install --frozen-lockfile
      - run: yarn test:workflow
      # - name: SonarCloud Scan
      #   if: ${{ github.actor != 'dependabot[bot]' }}
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # - name: Slack Notification
      #   if: ${{ github.actor != 'dependabot[bot]' }}
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_COLOR: ${{ job.status }}
      #     SLACK_TITLE: Feastables SMS PR Checks ${{ job.status }}
      #     SLACK_ICON: https://www.techwell.com/sites/default/files/stories/images/cropped_teasers/Beth%20Romanik/2018/integration.png
      #     SLACK_USERNAME: CI Action
